### ISSUE TITLE
Fatal Error for IDEA 2020.1

### ISSUE THREAD

**Issue by SvenAugustus** [oowekyala/intellij-javacc#15]
java.lang.Throwable: All stub element types should be created before index initialization is complete.
Please add the class containing stub element type constants to "stubElementTypeHolder" extension.
Registered extensions: [com.intellij.util.xml.stubs.DomElementTypeHolder, com.intellij.psi.impl.java.stubs.JavaStubElementTypes, com.intellij.coldFusion.model.psi.stubs.CfmlStubElementTypes, org.intellij.plugins.markdown.lang.MarkdownElementTypes, com.intellij.lang.properties.parsing.PropertiesElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyEmptyStubElementTypes, com.intellij.lang.aspectj.parsing.AspectJStubElementTypes, com.intellij.sql.psi.SqlCompositeElementTypes, com.intellij.sql.dialects.sql92.Sql92ElementTypes$Stubs, com.intellij.sql.dialects.db2.Db2ElementTypes$Stubs, com.intellij.sql.dialects.derby.DerbyElementTypes$Stubs, com.intellij.sql.dialects.exasol.ExaElementTypes$Stubs, com.intellij.sql.dialects.h2.H2ElementTypes$Stubs, com.intellij.sql.dialects.hive.HiveElementTypes$Stubs, com.intellij.sql.dialects.hsql.HsqlElementTypes$Stubs, com.intellij.sql.dialects.mysql.MysqlElementTypes$Stubs, com.intellij.sql.dialects.oracle.OraElementTypes$Stubs, com.intellij.sql.dialects.oraplus.OraPlusElementTypes$Stubs, com.intellij.sql.dialects.postgres.PgElementTypes$Stubs, com.intellij.sql.dialects.redshift.RsElementTypes$Stubs, com.intellij.sql.dialects.greenplum.GPlumElementTypes$Stubs, com.intellij.sql.dialects.sqlite.SqliteElementTypes$Stubs, com.intellij.sql.dialects.mssql.MsElementTypes$Stubs, com.intellij.sql.dialects.sybase.AseElementTypes$Stubs, com.intellij.sql.dialects.cassandra.CassElementTypes$Stubs, com.intellij.sql.dialects.vertica.VertElementTypes$Stubs, com.intellij.sql.dialects.snowflake.SFlakeElementTypes$Stubs, com.intellij.psi.css.impl.CssElementTypes, org.jetbrains.plugins.less.LESSElementTypes, io.protostuff.jetbrains.plugin.psi.stubs.StubElementTypeHolder, com.intellij.lang.javascript.JSStubElementTypes, com.intellij.lang.typescript.TypeScriptStubElementTypes, com.intellij.lang.javascript.flow.FlowJSElementTypes, com.intellij.lang.javascript.frameworks.jquery.JQueryCssFileImpl, com.intellij.lang.actionscript.ActionScriptElementTypes, com.intellij.lang.ecmascript6.ES6StubElementTypes, org.angular2.lang.html.parser.Angular2HtmlStubElementTypes, org.angular2.lang.expr.parser.Angular2StubElementTypes, org.angular2.entities.metadata.Angular2MetadataElementTypes, org.jetbrains.plugins.scala.lang.parser.ScalaElementType$, org.jetbrains.plugins.scala.lang.parser.ScalaParserDefinition$, org.jetbrains.plugins.scala.lang.parser.Scala3ParserDefinition$, org.jetbrains.plugins.scala.worksheet.WorksheetParserDefinition$, com.intellij.scala.ssp.lang.parser.SspElementTypes$, com.intellij.scala.play.language.parser.tokens.Play2ASTTokens, com.jetbrains.python.PyStubElementTypes, com.jetbrains.cython.psi.elementTypes.CythonStubElementTypes, org.jetbrains.kotlin.psi.stubs.elements.KtStubElementTypes]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.psi.stubs.IStubElementType.checkNotInstantiatedTooLate(IStubElementType.java:34)
	at com.intellij.psi.stubs.IStubElementType.<init>(IStubElementType.java:28)
	at com.github.oowekyala.ijcc.lang.psi.stubs.JccStubElementType.<init>(JccStubElementType.kt:13)
	at com.github.oowekyala.ijcc.lang.psi.stubs.NodeClassOwnerStubElementType.<init>(StubImplementations.kt:112)
	at com.github.oowekyala.ijcc.lang.psi.stubs.NonTerminalStubElementType.<init>(StubImplementations.kt:167)
	at com.github.oowekyala.ijcc.lang.psi.stubs.BnfProductionStubImpl$TYPE.<init>(StubImplementations.kt:201)
	at com.github.oowekyala.ijcc.lang.psi.stubs.BnfProductionStubImpl$TYPE.<clinit>(StubImplementations.kt:201)
	at com.github.oowekyala.ijcc.lang.psi.stubs.StubImplementationsKt.factory(StubImplementations.kt:86)
	at com.github.oowekyala.ijcc.lang.JccTypes.<clinit>(JccTypes.java:15)
	at com.github.oowekyala.ijcc.ide.highlight.JavaccHighlightingColors.<clinit>(JavaccHighlightingColors.kt:97)
	at com.github.oowekyala.ijcc.ide.highlight.JavaccColorSettingsPage.<init>(JavaccColorSettingsPage.kt:31)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:595)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:54)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:132)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:401)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:249)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:37)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:33)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:554)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:546)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:530)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:387)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:96)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:276)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:128)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:137)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:100)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:127)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:50)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by oowekyala** [comment]
This should be fixed in the latest version (1.6), let me know if it isn't. You'll be notified of the update in a few hours.
