### ISSUE TITLE
java.lang.AssertionError: No ID found for serializer BNF_PRODUCTION 

### ISSUE THREAD

**Issue by PHPirates** [oowekyala/intellij-javacc#32]
This was reported at https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/3292 and seems to be incorrectly attributed to our plugin

Type of JetBrains IDE (IntelliJ, PyCharm, etc.) and version

IntelliJ IDEA 2023.2.4 (build IU-232.10203.10)

Operating System

Windows 11.0 (amd64)

```
java.lang.AssertionError: No ID found for serializer BNF_PRODUCTION (com.github.oowekyala.ijcc.lang.psi.stubs.BnfProductionStubImpl$TYPE), external id:JCC_BNF_PRODUCTION, language:Language: JavaCC
	at com.intellij.psi.stubs.StubSerializerEnumerator.getClassId(StubSerializerEnumerator.java:78)
	at com.intellij.psi.stubs.StubSerializationHelper.writeSerializerId(StubSerializationHelper.java:40)
	at com.intellij.psi.stubs.StubSerializationHelper.writeSerializerId(StubSerializationHelper.java:12)
	at com.intellij.psi.stubs.StubTreeSerializerBase.writeSerializerId(StubTreeSerializerBase.java:140)
	at com.intellij.psi.stubs.StubTreeSerializerBase.serializeStubList(StubTreeSerializerBase.java:238)
	at com.intellij.psi.stubs.StubTreeSerializerBase.serializeRoot(StubTreeSerializerBase.java:166)
	at com.intellij.psi.stubs.StubTreeSerializerBase.serialize(StubTreeSerializerBase.java:78)
	at com.intellij.psi.stubs.SerializationManagerImpl.serialize(SerializationManagerImpl.java:199)
	at com.intellij.psi.stubs.SerializedStubTree.serializeStub(SerializedStubTree.java:56)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:218)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:181)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:147)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:313)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:304)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:162)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:39)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:249)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:61)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:22)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:294)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:64)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1614)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1483)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:676)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1435)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1408)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1355)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1750)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1747)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1767)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:826)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:314)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:70)
	at com.intellij.psi.stubs.StubIndexEx.getAllKeys(StubIndexEx.java:302)
	at nl.hannahsten.texifyidea.index.IndexUtilBase$getKeys$1.invoke(IndexUtilBase.kt:157)
	at nl.hannahsten.texifyidea.index.IndexUtilBase$getKeys$1.invoke(IndexUtilBase.kt:157)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at nl.hannahsten.texifyidea.index.IndexUtilBase.getKeys(IndexUtilBase.kt:157)
	at nl.hannahsten.texifyidea.index.IndexUtilBase.getItems(IndexUtilBase.kt:122)
	at nl.hannahsten.texifyidea.index.IndexCommandsUtilBase.getCommandsByNames(IndexCommandsUtilBase.kt:21)
	at nl.hannahsten.texifyidea.reference.CommandDefinitionReference.multiResolve(CommandDefinitionReference.kt:37)
	at nl.hannahsten.texifyidea.psi.impl.LatexCommandsImplMixin.getReferences(LatexCommandsImplMixin.kt:106)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:58)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:50)
	at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:76)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:226)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:222)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:525)
	at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:194)
	at com.intellij.codeInsight.TargetElementUtil.findReference(TargetElementUtil.java:93)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:167)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
	at com.i
```

**Comment by oowekyala** [comment]
Thanks for reporting, will look into it

**Comment by oowekyala** [comment]
This is caused by #31
